// Code generated by goctl. DO NOT EDIT.
// Source: contact.proto

package contactclient

import (
	"context"
	contact2 "tikstart/rpc/contact/contact"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateMessageRequest     = contact2.CreateMessageRequest
	Empty                    = contact2.Empty
	GetFriendsListRequest    = contact2.GetFriendsListRequest
	GetFriendsListResponse   = contact2.GetFriendsListResponse
	GetLatestMessageRequest  = contact2.GetLatestMessageRequest
	GetLatestMessageResponse = contact2.GetLatestMessageResponse
	GetMessageListRequest    = contact2.GetMessageListRequest
	GetMessageListResponse   = contact2.GetMessageListResponse
	LoseFriendsRequest       = contact2.LoseFriendsRequest
	MakeFriendsRequest       = contact2.MakeFriendsRequest
	Message                  = contact2.Message

	Contact interface {
		CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Empty, error)
		GetLatestMessage(ctx context.Context, in *GetLatestMessageRequest, opts ...grpc.CallOption) (*GetLatestMessageResponse, error)
		GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*GetMessageListResponse, error)
		MakeFriends(ctx context.Context, in *MakeFriendsRequest, opts ...grpc.CallOption) (*Empty, error)
		LoseFriends(ctx context.Context, in *LoseFriendsRequest, opts ...grpc.CallOption) (*Empty, error)
		GetFriendsList(ctx context.Context, in *GetFriendsListRequest, opts ...grpc.CallOption) (*GetFriendsListResponse, error)
	}

	defaultContact struct {
		cli zrpc.Client
	}
)

func NewContact(cli zrpc.Client) Contact {
	return &defaultContact{
		cli: cli,
	}
}

func (m *defaultContact) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := contact2.NewContactClient(m.cli.Conn())
	return client.CreateMessage(ctx, in, opts...)
}

func (m *defaultContact) GetLatestMessage(ctx context.Context, in *GetLatestMessageRequest, opts ...grpc.CallOption) (*GetLatestMessageResponse, error) {
	client := contact2.NewContactClient(m.cli.Conn())
	return client.GetLatestMessage(ctx, in, opts...)
}

func (m *defaultContact) GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*GetMessageListResponse, error) {
	client := contact2.NewContactClient(m.cli.Conn())
	return client.GetMessageList(ctx, in, opts...)
}

func (m *defaultContact) MakeFriends(ctx context.Context, in *MakeFriendsRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := contact2.NewContactClient(m.cli.Conn())
	return client.MakeFriends(ctx, in, opts...)
}

func (m *defaultContact) LoseFriends(ctx context.Context, in *LoseFriendsRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := contact2.NewContactClient(m.cli.Conn())
	return client.LoseFriends(ctx, in, opts...)
}

func (m *defaultContact) GetFriendsList(ctx context.Context, in *GetFriendsListRequest, opts ...grpc.CallOption) (*GetFriendsListResponse, error) {
	client := contact2.NewContactClient(m.cli.Conn())
	return client.GetFriendsList(ctx, in, opts...)
}
