// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"
	logic2 "tikstart/rpc/user/internal/logic"
	"tikstart/rpc/user/internal/svc"
	user2 "tikstart/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Ping(ctx context.Context, in *user2.PingRequest) (*user2.PingResponse, error) {
	l := logic2.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserServer) Create(ctx context.Context, in *user2.CreateRequest) (*user2.CreateResponse, error) {
	l := logic2.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *UserServer) QueryById(ctx context.Context, in *user2.QueryByIdRequest) (*user2.QueryResponse, error) {
	l := logic2.NewQueryByIdLogic(ctx, s.svcCtx)
	return l.QueryById(in)
}

func (s *UserServer) QueryByName(ctx context.Context, in *user2.QueryByNameRequest) (*user2.QueryResponse, error) {
	l := logic2.NewQueryByNameLogic(ctx, s.svcCtx)
	return l.QueryByName(in)
}
