// Code generated by goctl. DO NOT EDIT.
package types

type Empty struct {
}

type BasicResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterResponse struct {
	BasicResponse
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResponse struct {
	BasicResponse
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type User struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type GetUserInfoRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type GetUserInfoResponse struct {
	BasicResponse
	User User `json:"user"`
}
